### ISSUE TITLE
We need to standardize how generators function

### ISSUE THREAD

**Issue by lxndrdagreat** [epandco/unthink-cli#10]
Generators are going to be a key part of the tool. We need to figure out a few things.

- [x] How do we make the "generate" command extensible?
- [x] How do we organize the templates?
- [x] How are options to be handled?

**Comment by lxndrdagreat** [comment]
Currently looking into how we could handle subcommands, since it doesn't seem to be a natural thing for gluegun.

**Comment by lxndrdagreat** [comment]
@tommyphilyaw and @lukecjohnson I think I have subcommands figured out. With a folder structure like this:

```
commands/
  generate/
    generate.ts
    entry-generator.ts
```

`entry-generator.ts` looks like this:
```ts
const entry: GluegunCommand = {
  name: 'entry',
  hidden: true,

  run: async (toolbox: GluegunToolbox) => {

    toolbox.print.info('TODO: entry generator!');
  },
};
```

The `hidden: true` makes it so the root `help` is not filled with subcommands.

The last thing I need to figure out is if there is an easy, automatic way to make `unthink generate` show a list of subcommands.

**Comment by tommyphilyaw** [comment]
Ah ok. So gluegun naturally does this based on folder structure then? If you run `unthink g` without any args does it not show anything?

**Comment by lxndrdagreat** [comment]
Running `unthink g` will default to the _base_ command, so `generate.ts`.

**Comment by lxndrdagreat** [comment]
So I'm trying to figure out how to automate "help" for the base command.

**Comment by lxndrdagreat** [comment]
I'm not sure if doing this is some sort of taboo... but it works. Commit is here: https://github.com/epandco/unthink-cli/commit/564180a554474b8da8209eb1318c0d511f2fc667

```bash
unthink g
┌───────────┬──────────────────────────────┐
│ Generator │ Description                  │
├───────────┼──────────────────────────────┤
│ entry     │ Create a new Webpack entry   │
├───────────┼──────────────────────────────┤
│ resource  │ Create a new server Resource │
├───────────┼──────────────────────────────┤
│ riot      │ Create a new Riot Component  │
└───────────┴──────────────────────────────┘

```

**Comment by lukecjohnson** [comment]
Could the base `unthink g` command be a prompt giving you the ability to select what you want to generate? It would basically achieve the same purpose of listing all the possible subcommands but then would also have some functionality

**Comment by lxndrdagreat** [comment]
With this system, each generator is a proper command, meaning we can handle things like per-generator CLI arguments/options with gluegun.

Theory:

    unthink g riot path/to/my-component --no-script --no-styles

**Comment by lxndrdagreat** [comment]
@lukecjohnson and yes, that means that each generator can use the `prompt` system.

**Comment by lxndrdagreat** [comment]
Whether or not we want the root command to show a prompt is up for discussion.

**Comment by lxndrdagreat** [comment]
I _do_ want to enforce the naming convention for the files: `thing-generator.ts`.

**Comment by lukecjohnson** [comment]
Yeah each generator can still be a proper command like the one you provided, but if you don't provide any subcommands, then you get the prompt to select a generator.

`unthink g` ⟶ prompt with list of all generators
`unthink g entry sample-page` ⟶ bypasses prompt and runs entry generator

**Comment by lxndrdagreat** [comment]
I'm not sure if it is possible to have the prompt launch a subcommand. I'll have to look into it. Currently, I have to manually load the other modules to find out information about them.

**Comment by lukecjohnson** [comment]
This seems to work....

```
import { GluegunToolbox, GluegunCommand } from 'gluegun';
import entryGenerator from './entry-generator';

const generate: GluegunCommand = {
  name: 'generate',
  alias: ['g', 'gen'],
  description: 'Generate files from templates',

  run: async (toolbox: GluegunToolbox) => {
    entryGenerator.run(toolbox);
  },
};

export default generate;
```

Basically just importing `entryGenerator` and calling `entryGenerator.run(toolbox)`

**Comment by lxndrdagreat** [comment]
I don't think that's a good route to go. That means that the subcommand is getting pulled in and compiled with the root command, and might actually get imported again by gluegun at runtime.

**Comment by lxndrdagreat** [comment]
It's theoretically possible to run it that way with how I am importing them in the `for` loop.

**Comment by lxndrdagreat** [comment]
If we go with the root command prompting, we're also going to have to decide how subcommands work. I wasn't currently planning on having prompts in them - they would work off of arguments/options. If we run a command via a prompt, then we will have to have prompts inside that command.

**Comment by lukecjohnson** [comment]
Yeah that’s true, it does open the door to requiring a bunch of prompts. But I guess having the fallback prompts could be considered a better user experience. If it’s a command you use a lot, then you’ll know the sub commands and arguments you need, thus bypassing all the prompts. But if you don’t know the required arguments, it would be helpful. 

So probably a nice to have but definitely does make all the commands a bit more complex

**Comment by lxndrdagreat** [comment]
Let's plan on organizing templates by generator. So for "entry-generator" there would be `templates/entry/...`.

**Comment by lxndrdagreat** [comment]
I did a first draft of for the entry generator (#8).
Commit: 408aa72512516f7dbc394c60117fcc8f363c7999.

Need to clean things up and move helpful logic to extensions so they are available to other generators.

Also, need to handle errors. Hopefully avoiding lots of errors via having a lot of requirement tests up-front, but still need to wrap things just in case.

**Comment by lxndrdagreat** [comment]
First draft for the standalone Riot component generator is here: 6ceb40b5676996a6c83f740cc93b82cb266b01aa
