### ISSUE TITLE
Determine template configuration/manifest

### ISSUE THREAD

**Issue by lukecjohnson** [epandco/unthink-cli#103]
We need to nail down what a template's manifest file will look like. For reference, templates for Create React App have a `template.json` that look similar to what we're trying to do: https://github.com/facebook/create-react-app/tree/master/packages/cra-template

Other than dependencies, what else should be included?

**Comment by lxndrdagreat** [comment]
I actually lean away from having a separate manifest JSON now. I think the package.json could actually be utilized. Obviously, deps/devDeps can be pulled straight from it, but I also think we could just add an "unthink" block to the JSON and use that for anything else.

For example, that block could have:

```json
{
  "unthink": {
    "name": "Express Server Layer",
    "slug": "server",
    "path": "src/server"
  }
}
```

- `name` could be what eventually shows up in the CLI
- `slug` could be what gets used for the package scripts (to make "build" into "build-server")
- `path` could be where the source files get dumped

**Comment by lukecjohnson** [comment]
Closing this as it seems like we're moving away from this approach
