### ISSUE TITLE
Create standalone Riot template

### ISSUE THREAD

**Issue by lukecjohnson** [epandco/unthink-cli#104]
- [x] Create repo
- [ ] Build out template

We need to determine what all should be part of this template. The obvious components are:
- Entries directory
- Polyfills
- Sass directory with maybe some base styles
- Styleline config
- TS config
- Riot typings file
- Dev script
- Webpack configs
- Riot preprocessors

How should common files like the ESLint config be handled? Do templates/HTML files need to be handled if it is a client-only project?

**Comment by lukecjohnson** [comment]
@lxndrdagreat Any thoughts on how we should handle the webpack configs? There are currently explicit paths referenced like `path.join(_rootPath, 'src', 'client', 'entries')`, but this path could be different depending on if its a standalone client-only project or an integrated full stack project.

**Comment by lxndrdagreat** [comment]
Perhaps this should be read from the "unthink" block in the package.json?

If the templates are all set up like the following:

```json
{
  "unthink": {
    "templates": {
       "riot":  {
          "name": "template-riot",
          "slug": "riot",
          "path": "src/riot"
       } 
    }
  }
}
```

So the templates are set up that way, then the webpack config could read the path from `package.unthink.templates.riot`?

It seems messy, but I can't think of another way to handle the configuration we'll need...

**Comment by lukecjohnson** [comment]
Yeah we could use something like that for the webpack configs and `riot-preprocessors.js`. But the more I think of this, the more places I think of that will have problems like this. The npm scripts like `watch-sass`, `watch-public`, `lint-client`, `lint-sass`, etc. all have a path set as well.

Unfortunately, I can't think of many other solves without completely reworking the structure of the stack, but it just seems like it's going to get messy accounting for all the different places this issue could be
