### ISSUE TITLE
Add arguments/options/flags to specify templates

### ISSUE THREAD

**Issue by lukecjohnson** [epandco/unthink-cli#108]
We will need to add some sort of interface to specify templates on the `unthink init` command. 

There are two approaches to this that I can think of:
1.) There are default client/server templates that can be overridden with `--client` and `--server`
2.) There are no defaults - each template must be explicitly provided

With approach 1, if a `--client` or `--server` option is not provided, it would default to the Riot and Express templates. Flags like `--no-server` or `--no-client` could be used to create a standlone client or server project. Some examples:

```shell
# Create project with default templates

unthink init example-project
```

```shell
# Create project with Vue and default server

unthink init example-project --client vue
```

```shell
# Create standalone Riot project

unthink init example-project --no-server
```

With approach 2, a list of arguments could be provided for each template that should be used. Some examples:
```shell
# Usage

unthink init [project-name] [...templates]
```

```shell
# Create project with Vue and Express

unthink init example-project express vue
```

```shell
# Create standalone Riot project

unthink init example-project riot
```

Personally, I lean towards approach 1, but approach 2 could be a bit more extensible

**Comment by lxndrdagreat** [comment]
I'm fine with approach 1. Long term, the idea would be to have the features list in the CLI, but this is definitely good enough for a first version.

**Comment by lxndrdagreat** [comment]
@lukecjohnson the more I think about this, the more I like approach 2, though I still think we should have a "default".

**Comment by lukecjohnson** [comment]
@lxndrdagreat So are you thinking if no arguments are provided, it defaults to Express + Riot, but if any argument is provided, defaults are disregarded? Something like:

```shell
# Default Express + Riot

unthink init project-name
```

```shell
# Riot only

unthink init project-name riot
```

```shell
# Express + Vue

unthink init project-name express vue
```

**Comment by lxndrdagreat** [comment]
Exactly. I like the command structure better this way. It's more parsable to me than seeing a bunch of flags.
