### ISSUE TITLE
Create npm package for eslint config

### ISSUE THREAD

**Issue by lukecjohnson** [epandco/unthink-cli#109]
With separating the server/client templates and potentially creating new templates in the future, like a Vue template, changes to the eslint config would need to be made in several locations. We could create an npm package for our standard eslint config that could be used in all of the Typescript templates. The config could always be extended in a project if needed, but I think it would be a nice way to share the standard config across projects.

A useful guide on the topic: https://eslint.org/docs/developer-guide/shareable-configs

**Comment by lukecjohnson** [comment]
It looks like we could also do the same with the stylelint config: https://stylelint.io/user-guide/configure#extends

**Comment by lxndrdagreat** [comment]
A very early-on goal was to actually use our styleguide repo to house these. Going with packages would probably be easier to use.

**Comment by lukecjohnson** [comment]
Yeah the package approach would definitely make it easier to maintain across projects. Do you like the idea of just having separate repos for the packages? Or going with a monorepo style and keeping those packages in the styleguide repo - similar to how Airbnb handles it (https://github.com/airbnb/javascript)?

**Comment by lxndrdagreat** [comment]
I lean towards the monorepo for this. Each package is small/simple, so it kinda makes sense to me.
