### ISSUE TITLE
Add version page to stack

### ISSUE THREAD

**Issue by tommyphilyaw** [epandco/unthink-cli#12]
Need to add a `/version` or maybe `/stack/version` page to the stack that is always served up.

First pass would be:

- Add version resource to the stack
- Implement a version route that reads in the package.json file and display the version property
- Should not require authentication to view

No hard requirements on the look and feel of the page.

**Comment by lukecjohnson** [comment]
@tommyphilyaw Mind if I take a pass at this? Is there any other info that would be helpful on this page - like Unthink version or anything else?

**Comment by lxndrdagreat** [comment]
@lukecjohnson definitely go for it! Assign yourself to it and get started! 

> Unthink version

I don't want to include the CLI version. I feel like that would technically add possible vector information for a malicious attack; for example, there are attacks that are based on scripts checking websites' info pages for weak/unpatched/insecure versions.

**Comment by tommyphilyaw** [comment]
I agree @lxndrdagreat about leaving the CLI Version out.

I was not sure about the URL but maybe to ensure we park this at like `/unthink/version`. Purely so we aren't taking up like `/version` path that maybe would be used for something in a real project. 

Any thoughts? Again goal here is to put it in a well known place but out of the way.
