### ISSUE TITLE
Better baseline Sass styles

### ISSUE THREAD

**Issue by lxndrdagreat** [epandco/unthink-cli#16]
We need to determine and implement better starting styles in the client side of the stack.

- [ ] What are the bare minimum styles we need to have?
- [ ] How do we organize the Sass files?

**Comment by lukecjohnson** [comment]
Jumping in to give some of my thoughts…

For base styles, I think the starter project should really only include a `_base.scss` file with a few common base rules. Then additional modules can be added on a project-specific basis for things like global text styles. For the initial `_base.scss` file, I don't think it needs much more than something like this:
```
* {
  box-sizing: border-box;
  font-family: inherit;
}

*:before,
*:after {
  box-sizing: inherit;
}

body {
  margin: 0;
  padding: 0;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

---

For organization, I've personally been using a structure like this:
- mixins
    - responsive.scss
- modules
    - _base.scss
    - _text.scss
- variables
    - breakpoints.scss
    - colors.scss
    - fonts.scss

With the move to component based styles, I don't think theres a need to overcomplicate the structure with a bunch of folders like `layout`, `theme`, `utils`, etc - I think most things could be included in a more generic `modules` folder (could be named `partials` or anything else).

---

Lastly, I think we should try to switch to the new Sass module system ([https://css-tricks.com/introducing-sass-modules/](https://css-tricks.com/introducing-sass-modules/)). With this system we would use the `@use` keyword when we need to explicitly reference something in a module like a variable or mixin, and the `@forward` keyword when we just need to pass along a file, without needing to directly access something it contains, like bundling modules together in a `main.scss`.

Example:
```
component.riot

<style type=“ssss”>
  @use 'src/client/sass/variables/colors';

  :host {
    background-color: colors.$dark;
  }
</style>
```

```
main.scss

@forward 'modules/base';
@forward 'modules/text';
```


Any thoughts? @lxndrdagreat @Loganjenkins @JGamDonut

**Comment by lxndrdagreat** [comment]
@lukecjohnson I totally agree on the `@use` and `@forward`, and have started using them in projects. When we eventually get a styleguide for our Sass, I'd like to include these in it as a requirement.

Your `base` looks good to me. Maybe with the addition of a `font-size: 16px;` in the `body`. I would like to include our standard breakpoints vars and responsive mixins in the template project, since we use those on every project (even if they have to be adjusted).

> With the move to component based styles, I don't think theres a need to overcomplicate the structure with a bunch of folders like layout, theme, utils, etc - I think most things could be included in a more generic modules folder (could be named partials or anything else).

I totally agree. I think "modules" is a solid name for it.

**Comment by JGamDonut** [comment]
These are good implementation starts. With the component approach, I too agree with keeping the base as lean as possible. For me, this component style approach brings new thinking and methodology, and I'm in favor of its benefits. `@use` is pretty cool. 

I agree with consolidating partials like 'layout, utils, etc' into a single folder. I would add a folder or file for custom helper functions like unit conversion(pxtorem), unit stripping, arrow/caret building, etc.

I'm currently working on the css/sass styleguide and I'll ping you all to add with any other ideas, like the `@use` and `@forward`.

**Comment by lukecjohnson** [comment]
Yeah, a `functions` folder could be added when needed - as well as `vendor` and other things like that. I guess the main point is to not convolute the structure of the actual styles with abstractions like `layout`, `theme`, `foundation`, etc.

**Comment by lxndrdagreat** [comment]
@JGamDonut how many utility functions do we have? I ask, because if we only have a few, I lean towards having a single `utils` file, instead of a folder with several files that only have one or two things in them.

That said, if we want to have a "utilities" folder so when a project grows, then I guess that makes sense.

**Comment by lukecjohnson** [comment]
Closing issue here - discussion can continue at https://github.com/epandco/core-css
