### ISSUE TITLE
clean-build script calling OS-specific "rm"

### ISSUE THREAD

**Issue by lxndrdagreat** [epandco/unthink-cli#2]
In the `package.json`, the "clean-build" script utilizes `rm` which is not cross-platform.

**Comment by tommyphilyaw** [comment]
https://github.com/epandco/unthink-cli/commit/52ea16e149903d72daa0cc40014f796a30152186 should fix this. Included `shx` to do an os angostic move. As state in previous issue, gluegun included in this in there by default.

**Comment by lxndrdagreat** [comment]
Confirmed working on Windows.
