### ISSUE TITLE
Update init to use the filesystem tools in gluegun if possible.

### ISSUE THREAD

**Issue by tommyphilyaw** [epandco/unthink-cli#23]
Noticed a lot of useful functions under `toolbox.filesystem` that could have possibly been use to copy directory over and check if the directory is empty or exists period. Would be worth update init to use those and remove any packages we don't need.

**Comment by lxndrdagreat** [comment]
This is what they're using under the hood: https://github.com/szwacz/fs-jetpack

**Comment by lxndrdagreat** [comment]
I almost want to stick with fs-extra.

For comparison:
- https://www.npmjs.com/package/fs-extra
- https://www.npmjs.com/package/fs-jetpack

fs-extra looks like it is much more active, and has captured a much larger install base.

So the question is whether or not the extra dependency is worth that...

**Comment by tommyphilyaw** [comment]
Wow, yea fs-extra has a fairly larger user base it looks like from the weekly downloads anyway.

The main thing that stood out to me with the fs-jetpack tools was the the higher level commands like `exists` that replaces (which I'm certain I have not covered all the edge cases of):

```
    try {
      const existingFiles = await fsExtra.readdir(targetPath);
      if (existingFiles.length > 0) {
        toolbox.print.error(`${ path.resolve(targetPath) } is not empty.`);
        return;
      }
    } catch (e) {
      // lets just assume it's not a directory and move on.
    }

    try {
      await fsExtra.ensureDir(targetPath);
    } catch (e) {
      toolbox.print.error(`${ path.resolve(targetPath) } is not empty.`);
      return;
    }
```

with maybe something like:

```
    const exists = toolbox.filesystem.exists(targetPath);

    if (exists !== false) {
      toolbox.print.error(`${ path.resolve(targetPath) } is not empty.`);
      return;
    }
```

Haven't fully looked at the other commands though so whether it's worth fully converting to it not sure. It's just there anyway and was like oh that simplifies my life a little.

**Comment by tommyphilyaw** [comment]
Reviewed my usage of fs-extra and the code above was actually doing two things and neither library supported the main one which is determining if the directory existed and if exists if it was empty.

The original thought was to allow the `init` code to run if the target directory existed and was empty. Instead in the latest PR for init I opted to just bail if the path exists at all and let the user deal with it. I don't think this is un reasonable.

So I agree lets stick with fs-extra and I'm going to close this ticket.
