### ISSUE TITLE
"unthink" info in stack project

### ISSUE THREAD

**Issue by lxndrdagreat** [epandco/unthink-cli#24]
I know we've talked about this before. I would like to include some form of information in the stack about "unthink" being used. For now, it could be just the version of the CLI used when creating the project.

I would like to have the generators require the existence of the stack by first checking the CWD for "package.json" and then for "unthink". This will help the generators know that it is safe to place files in certain places.

Ideas for how to include it in the project:

- as "unthink" in the package.json
- as a separate "unthink.json" or ".unthinkrc" file

Requirements/needs:

- Needs to store the CLI's current version at time of project init
- Should make an extension with unthink-related functions (so we can do things like `toolbox.unthink.exists()`)

**Comment by tommyphilyaw** [comment]
Leaning toward placing it as a property on package.json unless there are any counter arguments you can think of where placing it in package.json is bad?

My original thought was something like 

```json
{
  "unthink": {
    "version": "1.0.1"
  }
}
```

Just in case we need more context and keeping neatly tucked away under `unthink`.

**Comment by lxndrdagreat** [comment]
I am fine with package.json. I definitely think we need to to be an object so we can add more to it later. I'm already thinking of making the path to entries configurable.
