### ISSUE TITLE
Component library

### ISSUE THREAD

**Issue by lukecjohnson** [epandco/unthink-cli#28]
I know we’ve had Riot component repos in the past but I think there’s room for a slightly more robust component library. Maybe `unthink-components`?

Perhaps there could be an integration with the CLI. It could be pretty cool to add a standardized component to your project, say a date-picker, with just a cli command.

Additionally, we could have a documentation site - could definitely just be a simple static site on GitHub Pages or something similar. It could serve as a showcase of all the components as well as basic documentation for each component (props list with descriptions). Thinking a simplified version of something like this: [https://material.io/develop/web/components/buttons/](https://material.io/develop/web/components/buttons/)

Any thoughts?

**Comment by lxndrdagreat** [comment]
I am currently evaluating a new version of how we would do a component library. A couple of concerns I've been mulling over:

- What is the best workflow for getting a component from the library into a project (making it part of the CLI might be a good way to do this)
- Should components be stored in a single repo or should they be separated out
- Should our internal components be public and open source

Integrations with the CLI would require some serious thought, depending on how we end up doing things. For one, I don't want the components to be a built-in part of the CLI; they would have to be plugins. Making them plugins means we could easily have public or private components.

> Additionally, we could have a documentation site

The documentation has been something we've looked at doing internally for a long time, and have tried a few different frameworks to accomplish it. Still evaluating where the most value is. Now that we have the stack, I think we can start seriously looking at this again.

**Comment by lukecjohnson** [comment]
Yeah I was thinking about the best workflow for getting a component from library to project and the CLI is an obvious solution but outside of that, I'm not sure. I don't think the approach of importing from a package is ideal because I'd think we'll want to have the component in our source code so we can make adjustments for project-specific styles or requirements. I guess you could just copy/paste from a repo or maybe the documentation site, but that doesn't seem super elegant.

What type of components do you think we'd want to be private? I'm assuming components like generic form elements or buttons would be fine to be open source
