### ISSUE TITLE
copy-templates script not cross-platform friendly

### ISSUE THREAD

**Issue by lxndrdagreat** [epandco/unthink-cli#3]
The "copy-templates" script in "package.json" does not work in Powershell on Windows.

The following error occurs:

    -e was unexpected at this time.

**Comment by tommyphilyaw** [comment]
https://github.com/epandco/unthink-cli/commit/52ea16e149903d72daa0cc40014f796a30152186 should fix this. Included `shx` to do a os agnostic copy. The default gluegun generated `package.json` was setup like that.

**Comment by lxndrdagreat** [comment]
Confirmed fixed on Windows.
