### ISSUE TITLE
Clean command for stack

### ISSUE THREAD

**Issue by tommyphilyaw** [epandco/unthink-cli#36]
Right now the lib folder is not cleaned before building and as a files are removed / renamed it leaves behind the old files in the lib folder.

This may need a quick conversation to talk through how this interacts with file watches and we may need to clean the `public` folder as well. For development I don't think we see the webpack files but when do a prod build it may not hurt to have it ensure those folders are deleted and recreated.

**Comment by tommyphilyaw** [comment]
@lxndrdagreat do you see an issue with this? I'm thinking we do something similar to the unthink-cli and bring in `shx` package rm lib/public on each build.

**Comment by lxndrdagreat** [comment]
Yeah, I think `shx` is a good way to go. Since we're bringing in `shx`, can we look at replacing the `copyfiles` lib (used to copy content/public folders) with `cp` via `shx`?

**Comment by tommyphilyaw** [comment]
Yeah it should be able to replace that easily and no need to have both.
