### ISSUE TITLE
init command not creating .gitignore when run from npm package

### ISSUE THREAD

**Issue by lxndrdagreat** [epandco/unthink-cli#37]
To reproduce:

- Install CLI via `npm install -g @epandco/unthink`.
- Run `unthink init test-project`

`.gitignore` file does not exist (tested on macos). Looking at the CLI in the global node_module folder (in my case, `/usr/local/lib/node_modules/@epandco/unthink/unthink-stack`), there is no ".gitignore" file there. Could the npm package not be including it?

Edit: I did a follow-up and tested the CLI project via `npm link`. It properly handles the ".gitignore" file.

**Comment by tommyphilyaw** [comment]
@lxndrdagreat running npm pack also included it properly which is basically a local version of what I think it sends up. 

Maybe it was removed on my local when I published it. Going to publish again.

**Comment by tommyphilyaw** [comment]
@lxndrdagreat actually lets talk about this in the morning before I publish anything. I have to bump a patch version to do it etc.

**Comment by lxndrdagreat** [comment]
Ends up that the `.gitignore` in the `unthink_stack` folder is getting renamed to `.npmignore` upon package installation.
