### ISSUE TITLE
Stylelint errors on inline style attributes with expressions

### ISSUE THREAD

**Issue by lxndrdagreat** [epandco/unthink-cli#4]
When using an inline style attribute with an expression, either simply templating in a dynamic value or using a Riot plugin like `styleAttribute`, stylelint throws errors, preventing commits.

When using an expression similar to `style="height: { state.itemHeight }"` the `value-keyword-case` rule in stylelint throws an error stating `Expected "state.itemHeight" to be "state.itemheight"`. Two easy, temporary workarounds for this issue are to either user bracket notation in the expression like `style="width: { state['itemHeight'] }"` or to use a function to return the correct value and include it in the expression like `style="width: { getItemHeight() }"`. For whatever reason stylelint doesn't throw errors with those solutions.

When using the `styleAttributes` plugin like this example from the Riot documentation, `style="{ styleAttribute({ 'color': 'red', 'font-size': `${fontSize}px`}) }"`, stylelint throws a `CssSyntaxError` stating `styleAttribute` is an `Unknown word`.

Possible solutions would be to configure these stylelint rules to accept these cases or to perhaps disable linting on inline style attributes all together as the only time inline styles should be used is in fringe cases like these.

**Comment by lxndrdagreat** [comment]
Interesting note from the Riot.js documentation: https://riot.js.org/documentation/#etc

    Expressions inside style tags are ignored.

I'm not that that is accurate.

**Comment by lxndrdagreat** [comment]
I think our utilization of stylelint on the Riot components is incorrect. I don't think it should be testing those files.

We _do_ have linting for the styles inside the components when compiling; that will have to be enough.

**Comment by lukecjohnson** [comment]
_**Update**_

It seems like this issue is mostly resolved if you do not wrap the expression in quotes. 
```
style={ getTextareaHeight() } ⟶ No error
```
 
```
style="{ getTextareaHeight() }" ⟶ CssSyntaxError (Unknown word)
```

Since our new Riot style guide mentions that the quotes are not required, this may be okay to close.

**Comment by lxndrdagreat** [comment]
OK. I'll close this out.
