### ISSUE TITLE
Stack V2 Documentation

### ISSUE THREAD

**Issue by lxndrdagreat** [epandco/unthink-cli#40]
How and where do we want to document how to use the stack? Do we set it up with the built-in wiki? Do we set up something with pages?

**Comment by tommyphilyaw** [comment]
I lean toward something like jekyll honestly or something in that vein which generates static site based on markdown.

Reading up on github pages they support [jekyll by default](https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll) and will actually run the build for the docs when publishing which is hinted [here](https://help.github.com/en/github/working-with-github-pages/about-github-pages#static-site-generators) as well. 

It would gives us the most flexibility I think. Thoughts?

**Comment by lxndrdagreat** [comment]
I was literally just coming here to start posting ideas.

I found this the other day, which uses your markdown files: https://docsify.js.org/#/?id=docsify

Jekyll is not a bad option either. Whatever we go with, I definitely lean towards just using GH Pages to host it; thought it might be kind of cool to build a doc site using the stack...

**Comment by tommyphilyaw** [comment]
I like the no "build" side of docsify. Lets roll with that and see where we land.

So I think we need to pull the docs folder up to the root so it can be hosted by github pages and in there we create cli docs and stack docs. 

Then in our generated READMES/UNTHINK readme for the stack maybe we link to the project docs ideally at the right version. I would like to know how we handle versions in this setup. Technically the docs are version along side the code and should be tagged etc.
