### ISSUE TITLE
eslint update for explicit-function-return-type

### ISSUE THREAD

**Issue by tommyphilyaw** [epandco/unthink-cli#41]
I think it would be ok to enable "[allowExpressions](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-function-return-type.md#allowexpressions)" for  @typescript-eslint/explicit-function-return-type.

There a few specific cases where I don't think it's necessary to define the return type when it's inferred from the expression for example in some cases the linter complains about this form (taken form the example todo):

```typescript
      'put': {
        // It wants the lambda function to specify its return type for handler
        handler: async ctx => serviceWrapper(() => {
          if (!ctx.params) {
            throw new NotAvailable();
          }

          const model = new TodoModel(ctx.body as TodoModel);
          return updateTodo(ctx.params.id?.toString(), model);
        }),
        middleware: [
          validateTodoMiddleware
        ]
      },
```

The return type can be inferred and if it there is a mismatch it will complain so I don't see a need to enforce that there and makes the code a little more verbose. The types for the args are inferred as well so I'm ok with the return type not being specified in these cases.

The change would be:

```
"@typescript-eslint/explicit-function-return-type": ["error", {
  "allowExpressions":  true
}],
```

**Comment by lxndrdagreat** [comment]
Sounds acceptable to me.

**Comment by tommyphilyaw** [comment]
Reopening this issue. I applied it to the eslintrc for the CLI not the stack. :(
