### ISSUE TITLE
Error during project init: ENOENT: no such file or directory, stat 'unthink-test/unthink-stack.md'

### ISSUE THREAD

**Issue by lxndrdagreat** [epandco/unthink-cli#67]
With latest version of the CLI, I get the following error when I run `unthink init unthink-test`:

```
Creating project at unthink-test/usr/local/lib/node_modules/@epandco/unthink/node_modules/gluegun/build/index.js:13
    throw up;
    ^

[Error: ENOENT: no such file or directory, stat 'unthink-test/unthink-stack.md'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'unthink-test/unthink-stack.md'
}
```

**Comment by matthewphilyaw** [comment]
I apparently changed the init command to move `unthink-stack.md` instead of `README.md` when we added docsify. I will correct this.

**Comment by matthewphilyaw** [comment]
@lxndrdagreat see the PR for this. In addition to the error above if you run the tool after doing `npm link` there was an additional error caused earlier on in the initi module with the `gitignore`. 

The `gitignore` is present in the target directory when the cli is installed via `npm link` but is stripped out when installing from npm. So modified the code to just force the move if it exists to resolve that edge case and shouldn't have any unintended side effects when installed from npm.
