### ISSUE TITLE
The public folder from client is added to the root public folder when adding images.

### ISSUE THREAD

**Issue by JGamDonut** [epandco/unthink-cli#68]
When adding images in a `/images/` folder under the client `/public/` folder during development, the entire path and contents of `/public/images/` are copied to the root `/public/` folder. So the final folder structure would look like `/public/public/images/`.

This seems to happen only when adding images AFTER running `npm start` or during development, but it works as expected if images already exist in the client `/public/images/` folder and then running `npm start`.

**Comment by lxndrdagreat** [comment]
This is an issue with the `cp` shell command. Need to alter the source path to include a `/.` after the `public`.

**Comment by matthewphilyaw** [comment]
@lxndrdagreat Has this been fixed yet? I finally ran into this the other day on one of my personal projects. 

I think it happens more often than just adding images. It seems to happen when anything triggers the public folder to be copied over - just can't remember exactly what I did.

**Comment by lxndrdagreat** [comment]
Yes, it is an overall issue with the public folder, not just images. I have a fix for it, but haven't implemented it yet.
