### ISSUE TITLE
Create server resource generator

### ISSUE THREAD

**Issue by lxndrdagreat** [epandco/unthink-cli#7]
We need a generator for a Resource.

Questions:

- Should it `extend` "ResourceBase" by default?
- What should it do for the "path" by default?

**Comment by lxndrdagreat** [comment]
Stub for this generator now exists.

**Comment by lxndrdagreat** [comment]
Putting this **on hold** for a bit, due to #21. We don't want to hold off on the Generator milestone while we get resources figured out.

**Comment by tommyphilyaw** [comment]
On the fence here about adding a generator for resources given the shorter form in v2. 

```typescript
import { expressResource } from '@epandco/unthink-foundation-express';

export default expressResource({
  name: 'foo', // a generator could fill this in
  basePath: '/foo', // and maybe this an optional parameter for it
  routes: [

  ]
});
```

It's just so minimal that is it worth it? Maybe we do it for completeness. Could obviously add more parameters to the generator to add a default 'view' or 'data' route but doesn't feel worth it.

**Comment by lxndrdagreat** [comment]
Yeah, I don't know that it is all that needed at this point. Especially compared to the other generators, which save you a ton of non-autocomplete-able boilerplate.

I'm fine with just closing this out for now.
