### ISSUE TITLE
Unthink stack packages added to CLI mistakenly added to package.json

### ISSUE THREAD

**Issue by lxndrdagreat** [epandco/unthink-cli#72]
I believe this was done in error: https://github.com/epandco/unthink-cli/blame/3b74fea5802ea5e9e6995e6222c93a10df78c01b/package.json#L52-L53

I don't think there is a reason for those to be dependencies for the CLI.

**Comment by matthewphilyaw** [comment]
Yup that was a mistake and good catch.
