### ISSUE TITLE
Riot TypeScript build script uses string.replace in a dangerous way

### ISSUE THREAD

**Issue by lxndrdagreat** [epandco/unthink-cli#75]
In the "riot-typescript-transformer.js" script, `const sourceFileWithoutExtension = sourceFile.replace('ts', '');` causes incorrect output when a component has a "ts" in the name (e.g., "presents-list.riot"). This causes issues down the chain.

Quick fix is to update the replace like so:

    const sourceFileWithoutExtension = sourceFile.replace('.ts', '.');

I would prefer a better fix in that whole function, so filenames and extensions are not being used for `if` conditions.

**Comment by matthewphilyaw** [comment]
Hmm. That seems a little dangerous still - what if you use dots to separate files names like `some.ts-file` or the extension started with `.ts`?

Maybe something like [this](https://repl.it/@matthewphilyaw/file-ext#index.js) is a slightly safer:

```javascript
function stripTSExtension(fileName) {
  if (!fileName.endsWith('.ts')) {
    return fileName;
  }

  return fileName.slice(0, -2);
}


const example1 = stripTSExtension('somets-file.riot'); // somets-file.riot
const example2 = stripTSExtension('some.ts-file.riot'); // some.ts-file.riot
const example3 = stripTSExtension('some.ts-file.ts'); // some.ts-file.
const example4 = stripTSExtension('some-file.ts'); // some-file.
const example5 = stripTSExtension('.ts'); // . <- no seriously the result is right there -- not a mistake! 
```

There might be even better ways just quick prototype to demonstrate the edge cases that might crop up. Not claiming it's bullet proof but the idea is to ensure that string ends with `.ts` before acting on it vs doing a replace.

**Comment by lxndrdagreat** [comment]
I do like that better. I'll make the changes.
